services:
  music-web-explorer:
    build: .
    container_name: music-web-explorer
    ports:
      - "8447:80"        # Nginx web server
      - "5157:5157"      # Flask API directa (opcional)
    volumes:
      # Base de datos (solo lectura)
      - /home/huan/gits/pollo/music-fuzzy/db/sqlite/musica.sqlite:/app/data/musica.sqlite:ro
      
      # Directorio de descargas (persistente)
      - /home/huan/Musica:/downloads
      
      # Logs (persistente)
      - /home/huan/contenedores/mfuzz/logs:/app/logs
      
      # Configuración SSH (clave específica para servidor remoto)
      # El entrypoint copiará la clave específica desde la ruta del config
      - /home/huan/.ssh:/tmp/host_ssh:ro
      
      # Configuración personalizada (opcional)
      - /home/huan/gits/pollo/mfuzz_docker_web/config.ini:/app/config.ini:ro
    
      - /mnt/NFS/moode/moode:/mnt/NFS/moode/moode:ro
 
      - /home/huan/gits/pollo/music-fuzzy/.content/:/home/huan/gits/pollo/music-fuzzy/.content/:ro

      - /home/huan/gits/pollo/music-fuzzy/ui/svg/:/home/huan/gits/pollo/music-fuzzy/ui/svg/:ro
    
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Madrid
      - USER=dietpi
      # Configuración de Telegram
      - TELEGRAM_BOT_TOKEN=5497935650:AAHZSY-Jw9OxQx2qwKcQtBH2D7ej9GyGaio
      - TELEGRAM_CHAT_ID=905051261
      # Habilitar/deshabilitar notificaciones
      - TELEGRAM_ENABLED=true

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Configuración adicional
networks:
  default:
    name: music-web-network